### ISSUE TITLE
implement SNOS job

### ISSUE THREAD

**Issue by apoorvsadana** [madara-alliance/madara-orchestrator#11]
Complete the SNOS job implementation over here - https://github.com/karnotxyz/madara-orchestrator/blob/2a9d77b7188afadefe3feba3347a909fc83299ed/crates/orchestrator/src/jobs/snos_job/mod.rs#L12

1. We plan to add an endpoint on Madara called `getSnosInput`. For now, we can assume this endpoint exists and we can call it to get the SNOS input - https://github.com/keep-starknet-strange/snos/blob/da26557078111b5d489154b162f3f810174f5b69/src/io/input.rs#L19
2. Use this input to execute the SNOS and get the PIE
3. Store the PIE in a database/S3. I think storing in S3 might make more sense as we won't really need to query the database
4. To add S3 support, we can add a generalised trait like we do for `database` and `queues` already

**Comment by sBaki92** [comment]
Hi, I would like to take it :)

**Comment by apoorvsadana** [comment]
Assigned!

**Comment by ocdbytes** [comment]
Assign this to me : )

**Comment by akhercha** [comment]
gm, I can take this one if it's free!

**Comment by apoorvsadana** [comment]
Yes, assigned!

**Comment by akhercha** [comment]
Done in https://github.com/madara-alliance/madara-orchestrator/pull/136
