### ISSUE TITLE
Database update logic fix

### ISSUE THREAD

**Issue by ocdbytes** [madara-alliance/madara-orchestrator#112]
- Current Behaviour : 
Current when we are updating the job using the mongo db `update_job_optimistically` function [code](https://github.com/madara-alliance/madara-orchestrator/blob/main/crates/orchestrator/src/database/mongodb/mod.rs#L57) Here we are using a `post_job_update` function to update the version and timestamp of the job. 

- Expected Behaviour : 
This should be happening in a single db transaction.

**Comment by PavitraAgarwal21** [comment]
@ocdbytes can i take up this issue

**Comment by ocdbytes** [comment]
@PavitraAgarwal21 

Unfortunately we are not taking external contributions right now.
