### ISSUE TITLE
remove `init_config` from tests and use `TestConfigBuilder`

### ISSUE THREAD

**Issue by apoorvsadana** [madara-alliance/madara-orchestrator#68]
We don't need to use `init_config` anymore. `TestConfigBuilder` should be able to replace it now.

**Comment by elielnfinic** [comment]
Can I work on this @apoorvsadana ?

**Comment by apoorvsadana** [comment]
Hey @elielnfinic, thanks for reaching out. Currently, there are four teams working on picking issues and we're trying to keep it to that for now. The main reason being to be more accountable and to be able to ship fast. So for now, we haven't opened issues to new contributors.

**Comment by elielnfinic** [comment]
Sounds good. Thank you.

**Comment by ocdbytes** [comment]
Ig we can close this @apoorvsadana
